#---------------------------------------------------------------
#       Application Configuration
#---------------------------------------------------------------

server:
  port: 8090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: student
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/student/**
        - id: school
          uri: http://localhost:8092
          predicates:
            - Path=/api/v1/school/**


#---------------------------------------------------------------
#       Eureka Configuration
#---------------------------------------------------------------
eureka:
  client:
    register-with-eureka: false