#---------------------------------------------------------------
#       Spring Configuration
#---------------------------------------------------------------

spring:
  application:
    name: student

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/students
    username: admin
    password: admin@123
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#---------------------------------------------------------------
#       Server Configuration
#---------------------------------------------------------------
server:
  port: 8091

#---------------------------------------------------------------
#       Eureka Configuration
#---------------------------------------------------------------
eureka:
  instance:
    hostname: localhost
    port: 8089
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

